### ISSUE TITLE
bug: iOS Corner points detection issue

### ISSUE THREAD

**Issue by Melynt3** [capawesome-team/capacitor-mlkit#126]
### Plugin(s)

- [x] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

5.3.0-dev.966ebeb.1703101506

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

I have problem trying to scan.
The corner point problem occurs only on iOS device in my case.

Can't understand why iOS coords are different on every angle im attempting to scan. Is there a way to lock it somehow?
I seems like i can get scan go through on lucky strike. 

Android works fine for me. 

my scan log:
```xml
{"rawValue":"ASDSADASDAS","bytes":[71,80,76,50,50,48,53,48,53,50,56,50,57],"cornerPoints":[[686,973],[681,1069],[165,1094],[174,1008]],"format":"CODE_128","valueType":"TEXT","displayValue":"ASDSADASDAS"}
⚡️  [log] - Detection Corner Points: [[57,519.7821655273438],[357,519.7821655273438],[357,644.7821655273438],[57,644.7821655273438]]
⚡️  [log] - Current Corner Points: [[686,973],[681,1069],[165,1094],[174,1008]]
⚡️  [log] - Conditions not met. Returning...
```
It makes problem because as u can see in logs scan never getting the value and enter never ending loop, when im commenting corner detection scanner works fine.

Would be greatfull for some tips/help

similar case: there is opened issue on this case.
https://github.com/capawesome-team/capacitor-mlkit/issues/115

### Expected behavior

I expect the success scan when catch barcode in my scan box.

### Reproduction

none

### Steps to reproduce

1. Add some logs to see detection coords and current cords 
2. Run demo barcode scanner on iOS device 
3. Try to scan from different angles 

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/core: 5.3.0
  @capacitor/ios: 5.0.5
  @capacitor/cli: 5.0.5
  @capacitor/android: 5.3.0

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Please create a screen recording and show the problem there.

**Comment by Melynt3** [comment]
the startScan code:

```ts
    private async startScan(): Promise<void> {
        document.querySelector('body')?.classList.add('barcode-scanning-active');

        const options: StartScanOptions = {
            formats: this.formats,
            lensFacing: this.lensFacing
        };

        const squareElementBoundingClientRect =
            this.squareElement?.nativeElement.getBoundingClientRect();
        const scaledRect = squareElementBoundingClientRect
            ? {
                left: squareElementBoundingClientRect.left * window.devicePixelRatio,
                right: squareElementBoundingClientRect.right * window.devicePixelRatio,
                top: squareElementBoundingClientRect.top * window.devicePixelRatio,
                bottom: squareElementBoundingClientRect.bottom * window.devicePixelRatio,
                width: squareElementBoundingClientRect.width * window.devicePixelRatio,
                height: squareElementBoundingClientRect.height * window.devicePixelRatio
            }
            : undefined;

        console.log('Scaled Rect:', scaledRect);

        const detectionCornerPoints = scaledRect
            ? [
                [scaledRect.left, scaledRect.top],
                [scaledRect.left + scaledRect.width, scaledRect.top],
                [
                    scaledRect.left + scaledRect.width,
                    scaledRect.top + scaledRect.height
                ],
                [scaledRect.left, scaledRect.top + scaledRect.height]
            ]
            : undefined;


        const listener = await BarcodeScanner.addListener(
            'barcodeScanned',
            async (event) => {
                this.ngZone.run(() => {
                    const cornerPoints = event.barcode.cornerPoints;
                    console.log('Scanned Corner Points:', cornerPoints);
                    console.log('Detection Corner Points:', detectionCornerPoints);

                    if (detectionCornerPoints && cornerPoints) {
                        if (
                            detectionCornerPoints[0][0] > cornerPoints[0][0] ||
                            detectionCornerPoints[0][1] > cornerPoints[0][1] ||
                            detectionCornerPoints[1][0] < cornerPoints[1][0] ||
                            detectionCornerPoints[1][1] > cornerPoints[1][1] ||
                            detectionCornerPoints[2][0] < cornerPoints[2][0] ||
                            detectionCornerPoints[2][1] < cornerPoints[2][1] ||
                            detectionCornerPoints[3][0] > cornerPoints[3][0] ||
                            detectionCornerPoints[3][1] < cornerPoints[3][1]
                        ) {
                            console.log('Condition not met, returning.');
                            return;
                        }
                    }
                    listener.remove();
                    this.closeModal(event.barcode);
                });
            }
        );

        console.log('Starting Barcode Scan...');
        await BarcodeScanner.startScan(options);
    }
```


Will that be enough?  In the last seconds of video im getting success, because my phone was in vertical position, only in this case it goes through.
https://github.com/capawesome-team/capacitor-mlkit/assets/45972864/83f9be6b-6fb3-4a7a-aaff-ede28c793637

**Comment by robingenz** [comment]
> [capawesome-team/capacitor-mlkit/assets/45972864/83f9be6b-6fb3-4a7a-aaff-ede28c793637](https://github.com/capawesome-team/capacitor-mlkit/assets/45972864/83f9be6b-6fb3-4a7a-aaff-ede28c793637)

I meant a screen recording of the device.

**Comment by Melynt3** [comment]
the screen is just scanning modal pointed on my barcode :D I just changed angle of camera

**Comment by Melynt3** [comment]
Do you need any screen record? I mean there's nothing to see there, just view of phone trying to scan barcode from different angle

**Comment by robingenz** [comment]
Yes, please upload a screen recording of the device.

**Comment by Melynt3** [comment]
This is how it works right now

Uploading scan-test.mov…

**Comment by Melynt3** [comment]
This is how it works right now

![](scan-test.mov)

https://github.com/capawesome-team/capacitor-mlkit/assets/45972864/514a1b3e-fb2c-4d55-8818-2a51fc1b041d

**Comment by robingenz** [comment]
Thank you for the video! Can you share an image file with the barcode so I can test it myself? 

Have you tried holding the camera further away, regardless of the angle?

**Comment by Melynt3** [comment]
> Thank you for the video! Can you share an image file with the barcode so I can test it myself?

Sure heres the img: 
![image](https://github.com/capawesome-team/capacitor-mlkit/assets/45972864/86ef0e7b-4fde-44ec-bccc-8c271d4d7469)


> Have you tried holding the camera further away, regardless of the angle?

 Ye i tired it from bigger distance and many other ways. The first vid that i send shows the diff in coords

**Comment by robingenz** [comment]
> I was thinking of flat workaround, in theory we could set the Y axis to the middle of our modal and the gave him eg. 200 height from there (100 top, 100 bottom) with 100% width. Which would make a box in the center of page with 200x100%
> 
> I think it would be nice to be able to set beacuse some devices may have problems with window scaling, it could prevent form scanning with whole modal when few barcodes would be in area, what do u think about it?

I'm not quite sure what you mean. You can already limit the area via JS. Do you want this to happen on a native level or how?

**Comment by Melynt3** [comment]
> > I was thinking of flat workaround, in theory we could set the Y axis to the middle of our modal and the gave him eg. 200 height from there (100 top, 100 bottom) with 100% width. Which would make a box in the center of page with 200x100%
> > I think it would be nice to be able to set beacuse some devices may have problems with window scaling, it could prevent form scanning with whole modal when few barcodes would be in area, what do u think about it?
> 
> I'm not quite sure what you mean. You can already limit the area via JS. Do you want this to happen on the native level or how?

I wrote it a bit wrong, I meant to mark the scanning field in the center, without using corner points. flat area in js.
And I was wondering if it had any right to exist

**Comment by robingenz** [comment]
There are users who want this area above or below. Not everyone wants it in the middle.

**Comment by Melynt3** [comment]
> There are users who want this area above or below. Not everyone wants it in the middle.

Ye, and i respect that, but was asking certainly about my case, it could skip the problem with part where code does not meet conditions, which bricks my app now somehow, because it sees the barcode immediately but detectionCornerPoints && cornerPoints not match.

```js
 if (detectionCornerPoints && cornerPoints) {
                        if (
                            detectionCornerPoints[0][0] > cornerPoints[0][0] ||
                            detectionCornerPoints[0][1] > cornerPoints[0][1] ||
                            detectionCornerPoints[1][0] < cornerPoints[1][0] ||
                            detectionCornerPoints[1][1] > cornerPoints[1][1] ||
                            detectionCornerPoints[2][0] < cornerPoints[2][0] ||
                            detectionCornerPoints[2][1] < cornerPoints[2][1] ||
                            detectionCornerPoints[3][0] > cornerPoints[3][0] ||
                            detectionCornerPoints[3][1] < cornerPoints[3][1]
                        ) {
                            console.log('Condition not met, returning.');  <------- this part
                            return;
                        }
                    }
                    listener.remove(); 
                    this.closeModal(event.barcode);
  ```

**Comment by robingenz** [comment]
I just fixed some corner points calculation issues in #127.
Please give this dev version a try and let me know if it resolves your issues:

```
npm i @capacitor-mlkit/barcode-scanning@5.3.0-dev.b1cf5ce.1708071895
```

**Comment by Melynt3** [comment]
ill check it right away, thanks.

**Comment by Melynt3** [comment]
Sorry for late response. 
I have installed this version but it still can go through while scanning eg. from the table 

```xml
{"barcode":{"bytes":[71,80,72,50,51,48,52,49,49,49,50,54],"rawValue":"GPH230411126","format":"CODE_128","displayValue":"GPH230411126","valueType":"TEXT","cornerPoints":[[257,886],[673,821],[684,918],[268,968]]}}
⚡️  [log] - Scanned Corner Points: [[257,886],[673,821],[684,918],[268,968]]
⚡️  [log] - Detection Corner Points: [[114,991.6085815429688],[714,991.6085815429688],[714,1241.608642578125],[114,1241.608642578125]]
⚡️  [log] - Condition not met, returning.
```

**Comment by robingenz** [comment]
In this case you need to debug it yourself. I cannot reproduce any issues with latest version. Feel free to create a PR with a fix.

**Comment by Melynt3** [comment]
![image](https://github.com/capawesome-team/capacitor-mlkit/assets/45972864/a4ea7212-1143-4156-b06d-eda9e3569854)

seems like detection corner points are rotated 90 degrees, any clue with that?

**Comment by robingenz** [comment]
Are you sure you use the latest version?

**Comment by Melynt3** [comment]
> Are you sure you use the latest version?

@capacitor-mlkit/barcode-scanning@5.3.0-dev.b1cf5ce.1708071895 this one

**Comment by robingenz** [comment]
Please give it a try with the latest version (5.4.0):

```
npm i @capacitor-mlkit/barcode-scanning@latest
```

**Comment by Melynt3** [comment]
> Please give it a try with the latest version (5.4.0):
> 
> ```
> npm i @capacitor-mlkit/barcode-scanning@latest
> ```

Hm i tested it and it seems to work, iOS is still working poorly, u have to move it some much to catch it, which gives feeling like it slowed.

When I hover over the barcode, I see the logs returning with results not being in scanning box, but after a while in the same position suddenly the code is treated as being in the field and the scan passes. Which is a bit strange.

Whole process of scanning works little bit slower overally

**Comment by robingenz** [comment]
Thanks for testing. That's weird. It works without problems for me. I recently shared a screen recording on X: https://x.com/robin_genz/status/1758536783414071431?s=46&t=k9Xz6D9ZXLbWibNDwFk3nQ

As I said, feel free to debug the issue on your end. PRs are welcome!

**Comment by Melynt3** [comment]
ill test it more tomorrow, it may be affected by camera losing focus from the center, and the code may be unreadable? 

Is this topic in ur schedule #119

**Comment by robingenz** [comment]
> Is this topic in ur schedule #119

It's still on my todo list but I don't have any ETA. Next, I'm working on the Capacitor 6 migration.

**Comment by Melynt3** [comment]
Almost got it works fine, but one thing is bugging me. The scanning box catches 40-50px below the box and the opposite is at the top, It kind of went downhill a bit for those. 

Thats the last problem im facing, did u set centering mechanism, or added some values to this scan box part in 5.4?

**Comment by robingenz** [comment]
No, your html seems to be okay.
