### ISSUE TITLE
EAN13 code detected as UPC-A

### ISSUE THREAD

**Issue by sertal70** [capawesome-team/capacitor-mlkit#139]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

5.4.0

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

EAN13 codes starting with 0 are detected as UPC-A code, dropping the leading 0 in the returned code.

### Expected behavior

EAN13 codes should be detected as they are, even when the code starts with 0.

### Reproduction

https://github.com/robingenz/capacitor-mlkit-plugin-demo

### Steps to reproduce

1. clone the official capacitor mlkit plugin demo repository 
2. build and start the app
3. select EAN13 format
4. scan the following EAN13 code:

<img width="320" alt="image" src="https://github.com/capawesome-team/capacitor-mlkit/assets/25665841/560d4acd-697a-4070-8def-b225fe37ccec">

5. In the console you'll get:

```json
{"barcode":{"bytes":[49,50,51,52,53,54,55,56,57,48,49,50],"rawValue":"123456789012","valueType":"PRODUCT","cornerPoints":[[277,1003],[270,481],[878,488],[872,998]],"format":"UPC_A","displayValue":"123456789012"}}
```

### Other information

I know that usually an UPC-A code can be "converted" into an EAN13 code by placing a leading 0, so maybe this could be the cause of the error. But the graphical render of a EAN13 code is quite different from an UPC-A code, as one can see from the following comparison:

<img width="591" alt="image" src="https://github.com/capawesome-team/capacitor-mlkit/assets/25665841/689dc5e7-33dd-458f-adc9-dd3139f14fb4">

### Capacitor doctor

$ npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.3
  @capacitor/core: 5.7.3
  @capacitor/android: 5.7.3
  @capacitor/ios: 5.7.3

Installed Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This should be an issue in the underlying library. Please create an issue in https://github.com/googlesamples/mlkit. This Capacitor plugin is just a wrapper around the ML Kit SDK.
