### ISSUE TITLE
 bug(barcode-scanning): googleBarcodeScannerModuleInstallProgress progress percentage is rounded incorrectly

### ISSUE THREAD

**Issue by luzader** [capawesome-team/capacitor-mlkit#144]
The googleBarcodeScannerModuleInstallProgress progress field, when it is valid, is only exactly 0 or exactly 1. Screenshot from inspector console:

![goobleBarcodeScannerModuleInstallProgress bug 2024-04-08 12-48-39](https://github.com/capawesome-team/capacitor-mlkit/assets/617962/798ad7d7-2ecf-49a5-b099-a800a40e987b)

(Installation over a slow cellular connection would hopefully have more events, but because of this bug they will mostly be 0%).

This is because the download progress is computed incorrectly:

https://github.com/capawesome-team/capacitor-mlkit/blob/cb63726e4a7c21822d13faa6987abfc169f733af/packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/ModuleInstallProgressListener.java#L35

The documentation specifies that this should vary from 0 to 100, so it really just needs a `100 *` prior to the integer cast. It is *very* difficult to test this code path, as the only way I have found is to start with a completely fresh AVD each time. Once a google play services module is installed, I have found no other way to remove it.

**Comment by robingenz** [comment]
Thank you! This will be fixed in the next version.

**Comment by luzader** [comment]
Thanks for the quick response. By the way, l I did find that if you remove google play services using adb and them reinstall it from the play store, it provides a more reliable test case.
