### ISSUE TITLE
bug: It can not working on a Modal

### ISSUE THREAD

**Issue by Coder7777** [capawesome-team/capacitor-mlkit#155]
### Plugin(s)

- [ ] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.0.0

### Platform(s)

- [ ] Android
- [ ] iOS
- [ ] Web

### Current behavior

I pop up a Modal first, then in that Modal page use 'startScan', it does not work, always shows black background only.

But, If I use in a normal page(non-modal page), it works fine. It seems the camera live stream cover by the first Modal page.

### Expected behavior

Show camera live stream

### Reproduction

...

### Steps to reproduce

https://github.com/capawesome-team/capacitor-mlkit/assets/17242425/6a3f7d4c-38ca-45ea-896a-fbcc4227394f

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
If it's works on non-modal pages there should be an issue with your css rules.
This is nothing I can fix within the plugin. I'm therefore closing this issue.
