### ISSUE TITLE
bug: ERESOLVE when updated to latest angular/cli/ionic

### ISSUE THREAD

**Issue by zavovi** [capawesome-team/capacitor-mlkit#165]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

5.4.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I cannot build without --force flag

### Expected behavior

build

### Reproduction

none

### Steps to reproduce

build it with latest environment

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/android: 6.1.0
  @capacitor/ios: 6.1.0

Installed Dependencies:

  @capacitor/android: 6.1.0
  @capacitor/cli: 6.1.0
  @capacitor/core: 6.1.0
  @capacitor/ios: 6.1.0

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
I am closing this topic as not enough information has been provided (e.g. missing reproduction).

**Comment by zavovi** [comment]
> I am closing this topic as not enough information has been provided (e.g. missing reproduction).

I updated it. It seems, that there should be changed only dependencies
