### ISSUE TITLE
feat: @capacitor-mlkit/translation should also have short language code as well.

### ISSUE THREAD

**Issue by Saqib92** [capawesome-team/capacitor-mlkit#172]
### Plugin(s)

- [ ] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [X] Translation

### Current problem

when getting language 

```
let langList = Object.entries(Language).map(([name, code]) => {
   return { name, code }; // English and en
});
```

My use case is with capacitor-community/text-to-speech whre speak method expect full code `en-US`.

### Preferred solution

Languages should have both short and full code. 

### Additional context

Translating text adn then using Text to Speech .

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Thank you for your request. Unfortunately, we are not planning to implement this feature. Therefore, I am closing this issue as not planned.
