### ISSUE TITLE
Huawei support

### ISSUE THREAD

**Issue by vladislavgolubev** [capawesome-team/capacitor-mlkit#174]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

This plugin supports huawei devices (without Google Play Services)?

### Preferred solution

support huawei devices

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
Yes, Huawei devices are supported but you have to use the [`startScan(...)`](https://capawesome.io/plugins/mlkit/barcode-scanning/#startscan) method and build the UI yourself.
