### ISSUE TITLE
bug(barcode-scanning): missing privacy manifest

### ISSUE THREAD

**Issue by akships** [capawesome-team/capacitor-mlkit#178]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

When I push my app to apple there is always this warning about privacy

<img width="771" alt="privacy-apple" src="https://github.com/user-attachments/assets/9bd41d57-298e-47c9-a84e-d57811fdd5d4">

### Preferred solution

I think this is due to dependency to MLKIT (which is dependent to an old version of GoogleToolboxForMac) version which is 5.0.0 currently and should be at least 6.0.0 or even 7.0.0.
On those latest versions the privacy issue is fixed.

Is it possible to update podspec to fix this or another solution in mind ? 

### Additional context

Using current latest version of package 6.1.0

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
According to the [changelog](https://developers.google.com/ml-kit/release-notes?hl=en#august_7_2024), the latest version for `GoogleMLKit/BarcodeScanning` is 5.0.0. This version is used by the plugin.

**Comment by Mercury-Ong** [comment]
Hi! I updated the GoogleMLKit/BarcodeScanning to 6.0.0 manually and ran pod update.
These packages were updated, and everything seems to be working fine. (for now)

`Installing CapacitorMlkitBarcodeScanning 6.1.0
Installing GoogleMLKit 6.0.0 (was 5.0.0)
Installing GoogleToolboxForMac 4.2.1 (was 2.3.2) 
Installing MLKitBarcodeScanning 5.0.0 (was 4.0.0)
Installing MLKitCommon 11.0.0 (was 10.0.0)
Installing MLKitVision 7.0.0 (was 6.0.0)`

The privacy policy was added on version 4.2.0 for GoogleToolboxForMac.

**Comment by robingenz** [comment]
I have created a PR to update the pods: https://github.com/capawesome-team/capacitor-mlkit/pull/179. Unfortunately, it contains breaking changes, so I can't merge the PR yet. You can use the pre-release in the meantime: https://github.com/capawesome-team/capacitor-mlkit/runs/29350483198

**Comment by robingenz** [comment]
Closed by #179. Please install the latest version using the `next` tag:

```
npm install @capacitor-mlkit/barcode-scanning@next
```

**Comment by geckozr** [comment]
While updating to ^7.0.0-next.1, I'm receiving this error:

```
[capacitor] ✖ update ios - failed!
[capacitor] [error] Analyzing dependencies
[capacitor]         [!] CocoaPods could not find compatible versions for pod "GoogleMLKit/BarcodeScanning":
[capacitor]         In Podfile:
[capacitor]         CapacitorMlkitBarcodeScanning (from `../../node_modules/@capacitor-mlkit/barcode-scanning`) was resolved to 7.0.0-next.1, which depends on
[capacitor]         GoogleMLKit/BarcodeScanning (= 7.0.0)
[capacitor]         
[capacitor]         Specs satisfying the `GoogleMLKit/BarcodeScanning (= 7.0.0)` dependency were found, but they required a higher minimum deployment target.
[capacitor]       
```
To correctly build the application, I had to increase the iOS platform version in my Podfile to: `platform :ios, '15.5'`

Is this supposed to be correct?

**Comment by robingenz** [comment]
Yes, see [BREAKING.md](https://github.com/capawesome-team/capacitor-mlkit/blob/next/packages/barcode-scanning/BREAKING.md#minimum-deployment-target). That's the reason why we can't publish a new latest version before the next major release.

**Comment by hoangqwe159** [comment]
@robingenz can you manage to merge the fix for GoogleMLKit/BarcodeScanning in version 6, please? My project cannot increase the the IOS platform version to 15.5; I believe it is the same for many others.

**Comment by robingenz** [comment]
@hoangqwe159 That's the problem. We have to increase the minimum deployment target to be able to merge it. This is a requirement from the ML Kit Barcode Scanning SDK.
