### ISSUE TITLE
feat: Ean13 with addons

### ISSUE THREAD

**Issue by SebastianAviles** [capawesome-team/capacitor-mlkit#190]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

I have products with EAN13 with addons, like 978-84-17751-81-3 00001, but the scanner only recognice 9788417751813 part, the rest 00001 is not captured.

### Preferred solution

I want to capture the 00001 part of code.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment]
This seems to be a problem with the underlying ML Kit SDK. Please report this issue to https://github.com/googlesamples/mlkit. This Capacitor plugin is only a wrapper for the ML Kit SDK and is not used for the evaluation of the barcodes. I'm therefore closing this issue.
