### ISSUE TITLE
bug: Aztec codes support

### ISSUE THREAD

**Issue by scr2em** [capawesome-team/capacitor-mlkit#200]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Version

6.1.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Hi, 
For aztec codes, I have tried the demo repo to scan them but it couldn't

### Expected behavior

In an interesting way, I used chatgpt to create a minimal ios app that uses AVFoundation directly, and it managed to scan the codes easily with 100% accuracy 

can anyone check why aztec codes specifically are hard to scan with the plugin? it should be able to scan them everytime 

### Reproduction

use your demo app 

### Steps to reproduce

try to scan these codes 

![image](https://github.com/user-attachments/assets/5f6e6111-1578-42c1-bd2f-bbf8b7726709)
![image](https://github.com/user-attachments/assets/ad8ff486-7f3d-45db-9238-a4ffda3336d1)

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: not installed
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by scr2em** [comment]
I did report this before, but this time it doesn't read them at all
https://github.com/capawesome-team/capacitor-mlkit/issues/164

**Comment by robingenz** [comment]
> In an interesting way, I used chatgpt to create a minimal ios app that uses AVFoundation directly, and it managed to scan the codes easily with 100% accuracy

This plugin uses ML Kit and not AVFoundation. But I will probably create a second implementation with AVFoundation soon.

Please share a screen recording of you reproducing it with the demo app.
