### ISSUE TITLE
bug: CocoaPods could not find compatible versions for pod "GoogleMLKit/Translate"

### ISSUE THREAD

**Issue by FlossyWeb** [capawesome-team/capacitor-mlkit#213]
### Plugin(s)

- [ ] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [X] Translation

### Version

7.0.0-next.2

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

npx cap sync fails to sync iOS

✖ Updating iOS native dependencies with pod install - failed!
✖ update ios 
[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "GoogleMLKit/Translate":
        In Podfile:
        CapacitorMlkitTranslation (from `../../node_modules/@capacitor-mlkit/translation`) was resolved to 7.0.0-next.2,
        which depends on
        GoogleMLKit/Translate (= 7.0.0)
        
        Specs satisfying the `GoogleMLKit/Translate (= 7.0.0)` dependency were found, but they required a higher minimum
        deployment target.

### Expected behavior

It should be able to sync

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

npm install @capacitor-mlkit/translation@next
npx cap sync

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
You need to set a higher minimum deployment target, see [Minimum Deployment Target](https://capawesome.io/plugins/mlkit/translation/#minimum-deployment-target).

**Comment by FlossyWeb** [comment]
@robingenz yes sorry I've passed on this too quickly
