### ISSUE TITLE
bug(barcode-scanning): `scan failed` on some Android devices

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-mlkit#38]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When calling the `scan(...)` the following error message appears in Android Studio:

```
scan failed.
com.google.mlkit.common.MlKitException: Failed to scan code.
at com.google.mlkit.vision.codescanner.internal.zze.zzc(com.google.android.gms:play-services-code-scanner@@16.0.0-beta3:4)
at com.google.mlkit.vision.codescanner.internal.zzf.onActivityResult(com.google.android.gms:play-services-code-scanner@@16.0.0-beta3:5)
at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:409)
at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:366)
at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:712)
at android.app.Activity.dispatchActivityResult(Activity.java:8951)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Expected behavior

No exception.

### Reproduction

-

### Steps to reproduce

1. Call the `scan(...)` method on Android

Seems to be reproducible only on some devices (e.g. Samsung S21 with Android 13).

### Capacitor doctor

-

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This might be related to https://issuetracker.google.com/issues/261579118?pli=1.

Give this workaround a try: 

```
However, I solved the problem by checking the availability of the API using ModuleInstallClient(https://developers.google.com/android/guides/module-install-apis) before launching the barcode scanner, and if not, actively installing it before launching it.
```

**Comment by BARNZ** [comment]
Getting the same error coming through in our logs as well but only for certain devices.

Could this plugin provide a function we can call to check module availability (via [https://developers.google.com/android/guides/module-install-apis](https://developers.google.com/android/guides/module-install-apis)).

Would a PR to add such a function be accepted? I feel like its something us developers should pretty much always first check when using `scan()`. Perhaps `scan` could even do the due diligence for us?

**Comment by robingenz** [comment]
Yes, I plan to take a look at this api. PRs are welcome.

**Comment by ericallenkrueger** [comment]
I'm having the same issue.  Last week (Friday 5-26-23) it failed once, then started working.  Today, same device, scanning is just broken.  Samsung Galaxy S10+

**Comment by barbar-binks** [comment]
any fix on this issue? It worked perfectly for a couple of hours and then I started getting an error, not exactly the same error as mentioned above. I get this: 

`Error: Falied to scan code`

**Comment by robingenz** [comment]
I plan to work on this issue this week.

**Comment by barbar-binks** [comment]
> I plan to work on this issue this week.

thank you for your help!

**Comment by levarberry** [comment]
Still waiting on a fix.     The workaround of ModuleInstalClient isn't clear on what needs to be added and where.

**Comment by robingenz** [comment]
I am already working on a PR: #44

**Comment by Waterdhavian** [comment]
@robingenz do you have an idea when you think you can finish the PR?

**Comment by robingenz** [comment]
@Waterdhavian I am very busy at the moment but will try to merge it in the next two weeks.

**Comment by barbar-binks** [comment]
Meanwhile, has anyone been able to find a workaround? @robingenz have you been able to pinpoint the cause of the issue?

**Comment by levarberry** [comment]
> Meanwhile, has anyone been able to find a workaround? @robingenz have you been able to pinpoint the cause of the issue?

I saw on Google's website that this is a known issue on their side as well.   They recommended using older versions of the play-services.   I tried that and it was  dishwater.   Had to downgrade too many things and it went down a hole that I no longer wanted to follow.

What is wierd is that my wife has a S20 Galaxy and have an S20 Galaxy.   Works on her phone and not my phone.   Has me thinking that some other app on her phone has installed the google-play-services on her phone.

**Comment by ericallenkrueger** [comment]
For our app, changing from scan() to startscan() fixed the issue.

**Comment by robingenz** [comment]
I have a possible solution ready so far but need help testing it as the problem cannot be reproduced on my Pixel 6a.
Please install this dev version:

```bash
npm install @capacitor-mlkit/barcode-scanning@5.0.0-dev.e6fceb5.1688799785
```

There are two new methods:
```ts
/**
 * Check if the Google Barcode Scanner module is available.
 *
 * Only available on Android.
 *
 * @since 5.1.0
 */
isGoogleBarcodeScannerModuleAvailable(): Promise<IsGoogleBarcodeScannerModuleAvailableResult>;
/**
 * Install the Google Barcode Scanner module.
 *
 * Only available on Android.
 *
 * @since 5.1.0
 */
installGoogleBarcodeScannerModule(): Promise<void>;
```

With those you can check if the Google Barcode Scanner module is available and install it if necessary.

I am looking forward to feedback!

**Comment by levarberry** [comment]
@robingenz  I will test this tonight.   THANK YOU SO MUCH!

**Comment by BARNZ** [comment]
Thanks @robingenz I'm in the same boat - I cannot repo but do have an end user who can. I'll get a build out to them over the next day or 2 with these changes and see if it helps things. Will keep you posted.

**Comment by robingenz** [comment]
Does anyone have feedback yet?

**Comment by BARNZ** [comment]
Have sent out a build for my problem user to test with - they are on the other side of the world so will hear back in the next 12 hours. Cheers

**Comment by levarberry** [comment]
@robingenz    Galaxy S20.  Still doesn't work.

**Comment by levarberry** [comment]
@robingenz  New error:

``` chunk-vendors.19d1a91d.js:33987 Error: The Google Barcode Scanner Module is not available. You must install it first.
    at returnResult (VM3:772:32)
    at win.androidBridge.onmessage (VM3:747:21)
logError @ chunk-vendors.19d1a91d.js:33987
```

**Comment by robingenz** [comment]
@levarberry Did you use the new method `installGoogleBarcodeScannerModule`?
What result did the `googleBarcodeScannerModuleInstallProgress` listener receive?

**Comment by levarberry** [comment]
@robingenz   I didn't change any Kotlin code.  I just added your package and sync it with Capacitor.   Not sure where to make changes.

**Comment by levarberry** [comment]
HOLD ON WAIT A MINUTE.

I added the functions to my local code:   
```
const handleScan = async () => {
  const ress = await BarcodeScanner.isGoogleBarcodeScannerModuleAvailable();
  console.log(ress);
  if(!ress.available){
    await BarcodeScanner.installGoogleBarcodeScannerModule()
  }
  const { barcodes } = await BarcodeScanner.scan({
    formats: [BarcodeFormat.Ean13, BarcodeFormat.UpcA, BarcodeFormat.UpcE],
  });
  const res = barcodes[0].rawValue;
 
  //const res = "9780200992930"

  if (res && res != "") {
    const ourDatabaseRes = await productStore.axApiBarcodeLookUp(res);
    if (ourDatabaseRes.id !== "0") {
      // const data = {
      //   id: ourDatabaseRes?.id,
      //   brand: ourDatabaseRes?.brand?.name,
      //   images: [ourDatabaseRes?.url],
      //   title: ourDatabaseRes?.title,
      //   description: ourDatabaseRes?.description,
      //   reviews: ourDatabaseRes?.reviews,
      //   status: ourDatabaseRes?.status,
      // };
     // await viewBarcodeResult(data, true);
     router.push(`/product-detail/${ourDatabaseRes.id}`)
    } else {
      const apiRes = await productStore.axProductBarcodeLookUp(res);
      console.log(apiRes);
      await viewBarcodeResult(apiRes, false);
    }

    //const resModal = await modalController.create({component:'modalLINK',componentProps:'data: fetchRes'})
  } else {
    alert("Could not find barcode in system");

    const upc = "079400061256"; //"852412007388";

    // }
  }
};
```
This seemed to work :)  BUT! only after I click it twice.   So I can make a work around for it when the app loads instead of doing it on click event.

**Comment by robingenz** [comment]
> BUT! only after I click it twice.

@levarberry This might be because the installation process is not finished when the Promise resolves. You have to wait for the event listener. But in that case it works now?

**Comment by Waterdhavian** [comment]
@robingenz works like a charm for me on my Samsung Galaxy S20+

For anyone who wants to debug this as well i will share my code:

I have div in my app that on click calls scanCode
```
<div (click)="scanCode()" class="button white">
        <span>{{ 'home.scan_code' | translate: {default: "Scan QR Code / Barcode"} }}</span>
</div>
```

`async scanCode() {
        // Current QR scanner: https://capawesome.io/blog/announcing-the-capacitor-mlkit-barcode-scanner-plugin/

        // Check camera permission
        await BarcodeScanner.requestPermissions();

        // Check if the Google ML Kit barcode scanner is available
        await BarcodeScanner.isGoogleBarcodeScannerModuleAvailable().then(async (data) => {
            if (data.available) {
                // Start the barcode scanner
                await this.startScanner().then(async (barcodes) => {
                    this.code = barcodes[0].rawValue;
                    this.scan();
                });
            } else {
                // Install the Google ML Kit barcode scanner
                await BarcodeScanner.installGoogleBarcodeScannerModule().then(async () => {
                    await this.startScanner().then(async (barcodes) => {
                        this.code = barcodes[0].rawValue;
                        this.scan();
                    });
                });
            }
        });
    }

    async startScanner() {
        const { barcodes } = await BarcodeScanner.scan({
            formats: [BarcodeFormat.QrCode, BarcodeFormat.Ean13]
        });
        return barcodes;
    }`

**Comment by robingenz** [comment]
@Waterdhavian That's great, thank you for your feedback! In that case I will release a new update with the fix.
Please note: You have to listen to the `googleBarcodeScannerModuleInstallProgress` listener. I have extended the documentation, see [`9ac6cdd` (#44)](https://github.com/capawesome-team/capacitor-mlkit/pull/44/commits/9ac6cdd8b21d53b2be56e3d6e0ff211dbf932b0e) .

**Comment by robingenz** [comment]
This is now fixed in `v5.0.3`:

```bash
npm i @capacitor-mlkit/barcode-scanning@5.0.3
```

**Comment by robingenz** [comment]
@levarberry Can you share the exact error message?

**Comment by levarberry** [comment]
I have since gone into the Pod file and change the dependency to v3.2.0.  I am no longer getting the exact error message.
