### ISSUE TITLE
feat: Face detection

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-mlkit#5]
**Is your feature request related to a problem? Please describe:**

The [ML Kit Face Detection API](https://developers.google.com/ml-kit/vision/face-detection) is not yet supported.

**Describe the solution you'd like:**

Add a Face Detection plugin.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by robingenz** [comment]
This issue can be sponsored if interested. Please contact us in advance by [email](mailto:support@capawesome.io) and mention the issue. PRs are also welcome.

**Comment by trancee** [comment]
@robingenz I would like to implement the Face Detection part, have you already done anything or should I start from scratch by adding a new package?

**Comment by robingenz** [comment]
Hi @trancee, no, I have not started yet. There was already a [similar request](https://github.com/capawesome-team/capacitor-mlkit/discussions/29) for another package, which I totally forgot. 🤦‍♂️ The process is that I prepare the boilerplate code once and then you can build on it. I'll do that this weekend and let you know then.

**Comment by robingenz** [comment]
@trancee Done, see #56. You can checkout my branch [`feat/face-detection`](https://github.com/capawesome-team/capacitor-mlkit/tree/feat/face-detection). Let me know if you need anything!

**Comment by trancee** [comment]
Quick question: the package.json version for `face-detection` package is at `5.0.3`. Is there a reason why it is that high already, and should I continue using it, or start from `0.0.1`?

**Comment by robingenz** [comment]
That's because all plugins in the repository should have the same version number. If someone wants to use several plugins from this repository, then the same version ensures that there are no version conflicts in the dependencies.

**Comment by robingenz** [comment]
So yes, please stay at that version.
