### ISSUE TITLE
feat: Face mesh detection

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-mlkit#6]
**Is your feature request related to a problem? Please describe:**

The [ML Kit Face Mesh Detection API](https://developers.google.com/ml-kit/vision/face-mesh-detection) is not yet supported.

**Describe the solution you'd like:**

Add a Face Mesh Detection plugin.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by robingenz** [comment]
This issue can be sponsored if interested. Please contact us in advance by [email](mailto:support@capawesome.io) and mention the issue. PRs are also welcome.

**Comment by robingenz** [comment]
@trancee I've prepared everything: #76

**Comment by trancee** [comment]
I just realized that there is no iOS implementation for this detection module. I assume since it's still in beta, the iOS version might come later?

**Comment by robingenz** [comment]
Okay, so let's just start with Android. 👍🏻
