### ISSUE TITLE
feat: Selfie segmentation

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-mlkit#8]
**Is your feature request related to a problem? Please describe:**

The [ML Kit Selfie Segmentation API](https://developers.google.com/ml-kit/vision/selfie-segmentation) is not yet supported.

**Describe the solution you'd like:**

Add a Selfie Segmentation plugin.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by robingenz** [comment]
This issue can be sponsored if interested. Please contact us in advance by [email](mailto:support@capawesome.io) and mention the issue. PRs are also welcome.

**Comment by trancee** [comment]
@robingenz I would like to implement this feature.

**Comment by robingenz** [comment]
@trancee That's great! I will create the boilerplate code for you.

**Comment by robingenz** [comment]
@trancee The boilerplate code is ready: #66 
As always, please create a PR for the `definitions.ts` file first.

**Comment by trancee** [comment]
@robingenz I guess this issue has been resolved :)

**Comment by robingenz** [comment]
Oh ^^Thanks @trancee 
Closed by #66
