### ISSUE TITLE
feat:  Show a box outline for IOS QR Code Scan

### ISSUE THREAD

**Issue by shapebuster** [capawesome-team/capacitor-mlkit#82]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

Android has a nice box outline for scanning the QR Code. I.e - where to position the qr code for it to scan.

A feature like this on ios would improve user experience. 

### Preferred solution

show box outline on ios camera when scanning qr code

**Comment by robingenz** [comment]
Hey, thanks for your request. Which plugin method are you referring to?

**Comment by paulosllvn** [comment]
> Hey, thanks for your request. Which plugin method are you referring to?
MLKit barcode scanner

**Comment by robingenz** [comment]
> MLKit barcode scanner

This is just the plugin name. Which method (see [API](https://capawesome.io/plugins/mlkit/barcode-scanning/#api)) are you referring to?

**Comment by paulosllvn** [comment]
> > MLKit barcode scanner
> 
> This is just the plugin name. Which method (see [API](https://capawesome.io/plugins/mlkit/barcode-scanning/#api)) are you referring to?

I am using BarcodeScanner.startScan()

**Comment by robingenz** [comment]
You need to manage the whole user interface yourself when using the "startScan(...)" method. 
I recommend testing the "scan(...)" method.
Please take a look at this guide: https://capawesome.io/blog/announcing-the-capacitor-mlkit-barcode-scanner-plugin/#scan-barcode-with-ready-to-use-interface

**Comment by paulosllvn** [comment]
> You need to manage the whole user interface yourself when using the "startScan(...)" method. I recommend testing the "scan(...)" method. Please take a look at this guide: https://capawesome.io/blog/announcing-the-capacitor-mlkit-barcode-scanner-plugin/#scan-barcode-with-ready-to-use-interface

I thought scan() was only for android using the google scanner?

**Comment by robingenz** [comment]
It's also available on iOS as described in the [documentation](https://capawesome.io/plugins/mlkit/barcode-scanning/#scan):

> Only available on Android and iOS.
