### ISSUE TITLE
bug: Running xcodebuild - failed! After installing barcode plugin on mac m1 (macOS Sonoma 14.0) / ios 17.

### ISSUE THREAD

**Issue by AntonGrafton** [capawesome-team/capacitor-mlkit#85]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

[error.txt](https://github.com/capawesome-team/capacitor-mlkit/files/12880643/error.txt)

### Expected behavior

After installing the barcode scanning plugin and trying to run the simulator i get a huge error. When i remove the plugin, everything can build properly.

### Reproduction

-

### Steps to reproduce

1. install plugin in a capacitatorjs project using mac m1 (macOS Sonoma 14.0) / ios 17.
2. See error

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request. I use a Mac M1 myself and have no problems. Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by AntonGrafton** [comment]
Hello, i could do that. But i just made a brand new project and installed the plugin and got this:

`could not find module 'Capacitor' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/antonsjolander/capacitor-grafton/ios/DerivedData/9DBB5611-90DD-4AF2-B954-427EB5BB5F75/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework/Modules/Capacitor.swiftmodule import Capacitor`


  "dependencies": {
    "@capacitor-mlkit/barcode-scanning": "^5.3.0",
    "@capacitor/android": "5.5.0",
    "@capacitor/app": "5.0.6",
    "@capacitor/core": "5.5.0",
    "@capacitor/haptics": "5.0.6",
    "@capacitor/ios": "5.5.0",
    "@capacitor/keyboard": "5.0.6",
    "@capacitor/status-bar": "5.0.6",
    "@ionic/vue": "^7.0.0",
    "@ionic/vue-router": "^7.0.0",
    "ionicons": "^7.0.0",
    "vue": "^3.2.45",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@capacitor/cli": "5.5.0",
    "@vitejs/plugin-legacy": "^4.0.2",
    "@vitejs/plugin-vue": "^4.0.0",
    "@vue/eslint-config-typescript": "^11.0.2",
    "@vue/test-utils": "^2.3.0",
    "cypress": "^12.7.0",
    "eslint": "^8.35.0",
    "eslint-plugin-vue": "^9.9.0",
    "jsdom": "^22.1.0",
    "typescript": "^5.1.6",
    "vite": "^4.3.9",
    "vitest": "^0.32.2",
    "vue-tsc": "^1.0.24"
  },

**Comment by AntonGrafton** [comment]
> Thank you for your request. I use a Mac M1 myself and have no problems. Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

https://github.com/AntonGrafton/capacitor-grafton

**Comment by robingenz** [comment]
Can you reproduce your issue with the [Capacitor ML Kit Plugin Demo](https://github.com/robingenz/capacitor-mlkit-plugin-demo) project?

**Comment by AntonGrafton** [comment]
> Can you reproduce your issue with the [Capacitor ML Kit Plugin Demo](https://github.com/robingenz/capacitor-mlkit-plugin-demo) project?

![image](https://github.com/capawesome-team/capacitor-mlkit/assets/136335927/be4b1eab-680b-49d9-b204-9889a472f1e4)

I get the same error after trying to run your  project on a IOS simulator. I'm using Xcode 15 by the way.

**Comment by robingenz** [comment]
The problem seems to affect only simulators. I have no problems on my physical iPhone 13.
The following fix worked for me: https://github.com/robingenz/capacitor-mlkit-plugin-demo/commit/484b919ff51f71b1e3b783b4305e06d600507858

**Comment by AntonGrafton** [comment]
> The problem seems to affect only simulators. I have no problems on my physical iPhone 13. The following fix worked for me: [robingenz/capacitor-mlkit-plugin-demo@484b919](https://github.com/robingenz/capacitor-mlkit-plugin-demo/commit/484b919ff51f71b1e3b783b4305e06d600507858)

Thank you Robin. I'll try! :)

**Comment by AntonGrafton** [comment]
Yep. That solved it! By adding your code to my podfile solved it. Thank you!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end

**Comment by seriousjelly** [comment]
I am having this issue:

- Latest XCode/MacOS version (fresh install)
- Latest Ionic (fresh install)
- Latest package version

Fails to build in simulator, although, I am able to open the generated XCode project and run in the simulator directly.

**Comment by Rdevc** [comment]
Hello!

Thank you for the provided solution, and I apologize in advance for responding to a closed issue.

Are you certain that this isn't merely activating a different 'Rosetta' way, serving as a quick fix rather than a real solution? It appears to be enabling a 'use all' approach, when it should be utilizing the ARM64 architecture instead. There will come a time when Apple will mandate 'no more Rosetta; build for ARM64.'

I'm also curious as to why other plugins do not encounter this issue.

Hope to hear from you and thank you in advance for reading and answering!

Kind regards

**Comment by robingenz** [comment]
> I'm also curious as to why other plugins do not encounter this issue.

This has nothing to do with the plugin but with the [pod](https://github.com/capawesome-team/capacitor-mlkit/blob/9a10f644f74e7ec15fd17ff571eb38f77ef17ede/packages/barcode-scanning/CapacitorMlkitBarcodeScanning.podspec#L16). You should therefore post your question in https://github.com/googlesamples/mlkit.

This is currently the only solution/workaround I have found. If anyone has a better solution, I would appreciate any tips.
