### ISSUE TITLE
bug: App including barcode scanning plugin builds, install but does not start on simulators

### ISSUE THREAD

**Issue by weeblr** [capawesome-team/capacitor-mlkit#87]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

Hello,
Trying to use the plugin in a small capacitor app, and test on ios simulator (android works fine).

App builds and install fine on simulator (see details below) but when launched:

- starts to open, showing a black screen for 1/2 second
- immediately closes

I have narrowed things down to the mlkit barcode plugin by disabling all other features/plugin in the app. I get the exact same behavior using your full demo app.

See below for error from log file and possibly relevant info.

Pretty new to this, so please bear with me if I'm missing something obvious. Let me know if there's some more log files that I can go through.

### Expected behavior

App starts and open its main window.

### Reproduction

https://github.com/robingenz/capacitor-mlkit-plugin-demo

### Steps to reproduce

1. Environment
McMini Sonoma, Xcode 15.0, capacitor 5.4.1

2. Config: defaults
3. Run either through capacitor CLI or from within Xcode. All default settings.
4. Error from logs CoreSimulator.log:

```
Oct 23 19:35:05 Mini-de-XXXX com.apple.CoreSimulator.simctl[27577] <Error>: launchApplicationWithID:options:pid:error:: Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "Simulator device returned an error for the requested operation." UserInfo={NSLocalizedDescription=Simulator device returned an error for the requested operation., NSUnderlyingError=0x60000034e940 {Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "dev.robingenz.capacitorjs.demo.mlkitplugins" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "dev.robingenz.capacitorjs.demo.mlkitplugins" failed., NSUnderlyingError=0x60000034e8e0 {Error Domain=FBProcessExit Code=64 "The process failed to launch." UserInfo={NSUnderlyingError=0x6000003ea400 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo=0x600001828bc0 (not displayed)}, BSErrorCodeDescription=launch-failed, NSLocalizedFailureReason=The process failed to launch.}}, FBSOpenApplicationRequestID=0x94bd, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace).}}, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace)., FBSOpenApplicationRequestID=0x94bd,
```

 

### Other information

- all work fine on android, both emulator and several physical devices
- I tried with and without an Apple ID entered in Xcode, currently without. Result is the same with an AppleId
- I have seen https://github.com/capawesome-team/capacitor-mlkit/issues/85 but I already applied this fix, which I came about from a different source
- tested on multiple simulators: iphone 15, 14, 13, exactly same result
- don't have a physical iphone to test ATM, should have one within a couple of days
- per various Google searches, I have many times:
  - rebooted machine
  - Cleared data in each simulator
  - made sure to Clean Build folder.. and Delete all files in Derived Data.. between each attempt
- I installed `@aparajita/capacitor-logger` and added some logging to syslog at various points during mlkit-barcode-scanning use in my code, but nothing appear in syslog. Which makes me think the app dies before it evens starts.
- At some point I saw a line in syslog that said:

```
Snapshot generation request for Bundle Id: com.weeblr.xxxxx app is denylisted
```

but I have not found it again since that one time. Not sure it adds anything to the error message listed above

### Capacitor doctor

capacitor-mlkit-plugin-demo % npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
Thank you for your request. Unfortunately, I can only help you if I can reproduce the problem. My demo app works fine for me. Please create a new app as [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository. Maybe then we will find the problem.

**Comment by weeblr** [comment]
Hi,

I thought you'd say that but if your demo app works for you - and not for me - I don't see why the simple repro app would not.

I think I'll wait to try and see what happens with a physical device first (should arrive today). Maybe I'll have a different outcome or some new message will appear in ether log .
I'll report back then.

Cheers

**Comment by robingenz** [comment]
Maybe I have a configuration in my demo app that is causing the problems and not the plugin.

> I think I'll wait to try and see what happens with a physical device first (should arrive today). 

Okay, that sounds good.

**Comment by weeblr** [comment]
> Maybe I have a configuration in my demo app that is causing the problems and not the plugin.

More likely I have misconfigured something as mine and the demo app behave the same. 
But the simple app is indeed best, too many moving parts otherwise

**Comment by weeblr** [comment]
Hi

So I got an iphone to test today (14, currently running ios16.6) and there the app works.

Therefore it looks like the issue is only with simulators.
BTW, you confirm the MLKit demo app works for you on an iphone 15 simulator - I'm on a macMini M2 if that matters

I'll try and do the simple app repro today.

Cheers

**Comment by robingenz** [comment]
I've only tested it on a real device last time. I will give it a try in the simulator.

**Comment by robingenz** [comment]
No problem here.

![grafik](https://github.com/capawesome-team/capacitor-mlkit/assets/13857929/a054c215-c063-4a50-ba37-8e86aea70632)

**Comment by robingenz** [comment]
Alright, in this case I am closing this issue.
