### ISSUE TITLE
bug: On IOS Emulator [error] - Error: Uncaught (in promise): Error: Not available on iOS

### ISSUE THREAD

**Issue by danisk89** [capawesome-team/capacitor-mlkit#89]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

If i try to start a new scan the plugin return me [error] - Error: Uncaught (in promise): Error: Not available on iOS

### Expected behavior

I want to use it on iOS. On Android is OK

### Reproduction

https://github.com/robingenz/capacitor-mlkit-plugin-demo.git

### Steps to reproduce

```
async scan(): Promise<void> {
    await BarcodeScanner.requestPermissions();

        // Check if the Google ML Kit barcode scanner is available
        await BarcodeScanner.isGoogleBarcodeScannerModuleAvailable().then(async (data) => {
            if (data.available) {
                // Start the barcode scanner
                await this.startScanner().then(async (barcodes) => {
                    var code = barcodes[0].rawValue;
                    console.log(code);
                });
            } else {
                // Install the Google ML Kit barcode scanner
                await BarcodeScanner.installGoogleBarcodeScannerModule().then(async () => {
                    await this.startScanner().then(async (barcodes) => {
                        var code = barcodes[0].rawValue;
                        console.log(code);
                    });
                });
            }
        });
  }

  async startScanner() {
    const { barcodes } = await BarcodeScanner.scan({
        formats: [BarcodeFormat.QrCode, BarcodeFormat.Ean13]
    });
    return barcodes;
}

  async requestPermissions(): Promise<boolean> {
    const { camera } = await BarcodeScanner.requestPermissions();
    return camera === 'granted' || camera === 'limited';
  }

  async presentAlert(): Promise<void> {
    console.log("Non va");
  }
```

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/ios: 5.4.1
  @capacitor/android: 5.4.1

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
`isGoogleBarcodeScannerModuleAvailable` is not available on iOS, see [documentation](https://capawesome.io/plugins/mlkit/barcode-scanning/#isgooglebarcodescannermoduleavailable):

```
Only available on Android.
```

Therefore, you should call this method only on Android.

**Comment by danisk89** [comment]
Ok, thank you so much. But if i want to use this plugin on ios, how to do? I tried on emulator and doesn't work

**Comment by robingenz** [comment]
I am not quiet sure what you mean. You can just call the following method (for example) on iOS:

```ts
const scan = async () => {
  const { barcodes } = await BarcodeScanner.scan({
    formats: [BarcodeFormat.QrCode],
  });
  return barcodes;
};
```

But you should call `isGoogleBarcodeScannerModuleAvailable` only on Android. Therefore just check the platform, see https://capacitorjs.com/docs/core-apis/web#getplatform

**Comment by danisk89** [comment]
Ok thanks a lot!! Should it work on ios xcode emulator?

**Comment by robingenz** [comment]
I haven't tried it.
