### ISSUE TITLE
Bundle Google Play barcode scanning capabilities instead of having to download

### ISSUE THREAD

**Issue by jpike88** [capawesome-team/capacitor-mlkit#90]
### Plugin(s)

- [ ] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

`isGoogleBarcodeScannerModuleAvailable` and `installGoogleBarcodeScannerModule`... what if the app is offline?

How can I bundle dependencies in such a way that I don't have to do that check?

### Preferred solution

Don't download dependencies via a line of code in my app.... bundle what's needed already like a normal app.

**Comment by jpike88** [comment]
I'm an idiot, I see this table. Though Google didn't make it easy to figure out!!!

![Screenshot 2023-11-03 at 15 32 17](https://github.com/capawesome-team/capacitor-mlkit/assets/9585787/3042e5f9-9d34-4866-9000-708a8b202a9d)

Is the code that checks/installs the barcode module kind of more for simulators etc? I can see that because the line is in the manifest, that should mean the module is downloaded at the time our app is downloaded meaning that `isGoogleBarcodeScannerModuleAvailable` will always return true on apps downloaded from the play store?

**Comment by robingenz** [comment]
No, unfortunately not. You also need to check this in production mode. You might want to take a look at this issue: https://github.com/capawesome-team/capacitor-mlkit/issues/38

**Comment by jpike88** [comment]
No surprise, Android development be like that. Thanks I'll look.
