### ISSUE TITLE
feat: Barcode scanner sometimes get bad value of EAN13

### ISSUE THREAD

**Issue by zavovi** [capawesome-team/capacitor-mlkit#95]
### Plugin(s)

- [X] Barcode Scanning
- [ ] Face Detection
- [ ] Face Mesh Detection
- [ ] Selfie Segmentation
- [ ] Translation

### Current problem

Hello, I am using your barcode scanner in my new app and sometimes the read data are bad. 

### Preferred solution

Please, is it possible to add some settings for read it twice or three times and compare? Or some any other alghoritm for check, if it is ok?

Thank you very much!

**Comment by robingenz** [comment]
This is already possible if you use the "startScan(...)" method and create the user interface yourself. There you have full control and can decide for yourself when you want to stop the scan.
Therefore, I do not plan to add this feature to the "scan(...)" method.

**Comment by robingenz** [comment]
Sure, this is the official demo app: https://github.com/robingenz/capacitor-mlkit-plugin-demo

**Comment by zavovi** [comment]
Thank you very much, that solved my issue! I reworked whole par of reading EAN in my app.
